### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by trapas**

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by mkutlak** [comment]
@trapas add to whitelist

**Comment by mkutlak** [comment]
:no_entry: wrong dirs

**Comment by ernestask** [comment]
> Can one of the admins verify this patch?

Having an existential crisis, aren’t we?

**Comment by ernestask** [comment]
Seems better now.

**Comment by ernestask** [comment]
(Some more force-pushing to follow to test existing PR checking)

**Comment by mkutlak** [comment]
LGTM, good bot @trapas

**Pull request merged**
