### PR TITLE
Duplicate container crashes

### PR DESCRIPTION
**Pull request by marusak**
Related to #1270 
This is the simplest solution. I do **not** insist on merging this PR. It is more like  _conversation starter_, so we can find the best solution.

This keeps the whole dumpdir event when the same crash happened in two different containers. But it deduplicates the same problem from one container.

There are many options, how to improve this, but in each and every of theme  is some catch, that is way to complex to solve.

Options @jfilak @mhabrnal @xsuchy ?

### CODE REVIEW

**Comment by mhabrnal** [comment]
@marusak I have the same opinion about this issue as the previous week. I think this solution is easiest and it's a good enought for the beginning.

**Comment by jfilak** [comment]
OK. I we can merge this PR once you describe the use case when you want to see the crash appearing in different containers. Please do not think it is a common knowledge. I had to think about it at least for a minute and I am not sure I found the same reason for this PR as you.

**Comment by marusak** [comment]
Ok, I see what you mean, that usually users/admins do not care about specific containers that much. However this makes more sense when I assume user using Cockpit.
Story time:
I, as a devops, test my App in containers. Testing is sometimes interupted and does not finish. It happened again so I use Cockpit to quickly check about the container.
I see this:
ok
However, If I looked further I would see that in previous container there was problem caught by ABRT.
wrong (of course, there could be like 400 of these containers, not only 3 :) )
I would immediately know, that there is something happening if I saw the exclamation mark on containers, in which problem occurred.

**Comment by jfilak** [comment]
Good, we are on the same page. Please, try to update the commit message with this particular use case and we can merge this PR.

**Comment by marusak** [comment]
@jfilak updated

**Comment by mkutlak** [comment]
test this please

**Pull request merged**
