### PR TITLE
Fix acquiring of D-Bus name in abrtd

### PR DESCRIPTION
**Pull request by jfilak**
It does not work because own main loop ignores `g_bus_own_name`.
I have found out this unpleasant state of abrtd when I was working on the first patch in this pull request.

### CODE REVIEW

**Comment by mmilata** [comment]
Does `wip_` in the branch name mean it shouldn't be reviewed yet?

**Comment by jfilak** [comment]
D`Oh, sorry, I was to lazy to rename the branch. You can review it, if you have time. Thanks!

**Comment by jfilak** [comment]
OK, I am going to update this pull request.

**Comment by jfilak** [comment]
This pull request is obsoleted by #909.

**Pull request closed without merging**
