### PR TITLE
ccpp: add %h and %e parameter into abrt-hook-ccpp

### PR DESCRIPTION
**Pull request by mhabrnal**
Without this commit core_pattern's parameters %h and %e was not
    translated at all.
    
    Due to 51531e9ea72af09571688a20f00e55cad5fe9c3a, %e has to be placed
    at the very end of the command in core_pattern.
    
    Example:
    If 'core_pattern = core.%h.%e.%p.%t' the result was
    core.%h.sleep.26284.1469805542 not core.myshostmane.sleep.26284.1469805542.
    
    Related to #1587891

### CODE REVIEW

**Comment by jfilak** [comment]
Nice test. Good job! What about to add a test with `%e` substituted by a string with a space - `pthread_setname_np`?

**Comment by jfilak** [comment]
Otherwise, I do find this PR ready to be merged ;)

**Comment by mhabrnal** [comment]
@jfilak I tried `pthread_setname_np` to set name containing space and it didn't work well. So I decided to obtain executable filename from file followed by a symlink /proc/PID/exe (if it exists).

**Comment by jfilak** [comment]
@mhabrnal are you going to update the test too?

**Comment by jfilak** [comment]
@mhabrnal Actually, what you mean by "it didn't work well"? Are you going to write a note about this decision into the commit message or as comment in the code?

**Comment by mhabrnal** [comment]
@jfilak If I set thread name containing spaces, an only first word is used. I am going to update test and commit message as well.

**Comment by jfilak** [comment]
Put the %e parameter into quotes then.

**Comment by jfilak** [comment]
Or you need to join all the argv values after the index 9 by space.

**Comment by mhabrnal** [comment]
I tied the quotes and it did work as expected, the idea of joining argv values after the index 9 come to my mind to, but I decided to do it the same way as is done in systemd-coredump. I like this approach the most.

**Pull request merged**
