### PR TITLE
Abrt python fixes

### PR DESCRIPTION
**Pull request by sorki**
Few improvements and bugfixes. Related to new cli.

One unrelated cli commit removing dead code included.

### CODE REVIEW

**Comment by jfilak** [comment]
Looks good! ACK from me. @mbrysa, can you please review the Python code?

**Comment by sorki** [comment]
- moved id and short_id from utils to Problem class as properties
- python3 compat - hashlib instead of sha
- added test for new properties

**Comment by jfilak** [comment]
I just want to make sure you intentionally omitted tests for `non_reportable` and `non_reportable_reason`.  Or those things are not properties?

**Comment by sorki** [comment]
Will add these. They are trivial but nice to have anyway..

**Comment by sorki** [comment]
Fixed both issues. Added setters for non_reportable properties

**Comment by sorki** [comment]
Removed leftover print

**Comment by mbrysa** [comment]
Why is the property for `not-reportable` called `non_reportable`?

**Comment by sorki** [comment]
not-reportable is not syntactically acceptable in python

**Comment by sorki** [comment]
also it should be renamed to not_reportable to comply with other elements like reported_to

**Comment by sorki** [comment]
sed s/non_reportable/not_reportable/g

**Comment by mbrysa** [comment]
Thank you!

**Pull request merged**
