### PR TITLE
WIP: The wheel group members are allowed to see all problems without password

### PR DESCRIPTION
**Pull request by jfilak**
Originally submitted by @hadess : https://lists.fedorahosted.org/pipermail/crash-catcher/2015-February/005583.html. The current implementation has been proposed by @Catanzaro.

### CODE REVIEW

**Comment by jfilak** [comment]
https://lists.fedorahosted.org/pipermail/crash-catcher/2015-April/005597.html
https://fedorahosted.org/fesco/ticket/1117

**Comment by sorki** [comment]
@trapas test this please

**Comment by mhabrnal** [comment]
@jfilak do you have any plans with this pull request? What else have to be done the pull request can be merged.

**Comment by mhabrnal** [comment]
Closing the pull request due to no changes for more than 2 years. If someone wants to finish this work, all commits stay in ```admins_dbus_polkit``` branch.

**Pull request closed without merging**
