### PR TITLE
fix for MCE events: Bug 1613182 - abrt-cli ignores rsyslog host info …

### PR DESCRIPTION
**Pull request by clime**
…and incorrectly assumes that the receiving host had a problem

Also adds fixes for tests because host name in test input files now matters. Test input files can now have an optional suffix ".template" and contain tags `:HOSTNAME:` or `:FULL_HOSTNAME:` which gets replaced by actual values on a machine where tests are run by new `prepare-data` script.

Note that this addition newly requires a short or long hostname to be present before "kernel: " string. If it is not present, the message is ignored.

### CODE REVIEW

**Comment by mkutlak** [comment]
test this please

**Comment by xsuchy** [comment]
test this please

**Comment by clime** [comment]
Should be ok now.

**Comment by mkutlak** [comment]
LGTM. Great job!


Just two things that need fixing.

 - We usually try to follow the following format of GIT commits.
```
topic: Short description of changes made in the commit

Longer description of changes made in the commit*

Related: List of related Bugzillas*
```
This makes it easier for us to find old relevant commits in the git log history, and to create new releases of abrt.


 - And the last thing is coding style - `{}` brackets  after `if, else, ...` should be always placed on the new line.

**Comment by clime** [comment]
Hello, I have added the commit with fixed formatting and the message. Can you check? I guess I should squash the commits in the end..

**Comment by clime** [comment]
Hello, I have added the commit with fixed formatting and the message. Can you check? I guess I should squash the commits in the end..

**Comment by mkutlak** [comment]
Thank you @clime

**Pull request merged**
