### PR TITLE
Switch to Python 3

### PR DESCRIPTION
**Pull request by jfilak**

### CODE REVIEW

**Comment by mhabrnal** [comment]
Package python3-systemd doesn't exist on Fedora 22, can you do the spec file adaptive?

**Comment by jfilak** [comment]
Sure, I was thinking about that but it was so easy to push this version, but I have to admit that it was a bad idea. I will not be so lazy next time.

**Comment by jfilak** [comment]
Hmm, I forgot that there is no python3-dmidecode in Fedora 22, so I cannot make the Python3 requires conditional. Sorry, you have to test it on Rawhide.

**Comment by mhabrnal** [comment]
I tested it on Rawhide and It looks good to me.

**Pull request merged**
