### PR TITLE
plugins: Allow abrt-retrace-client to be optional at build time

### PR DESCRIPTION
**Pull request by bkylerussell**

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
ok to test

**Comment by bkylerussell** [comment]
Looks like I can't access the link, so I can't tell what failed.  I don't see any failures if I run `make check` locally.  If there's a problem with the changeset, I'll be glad to look at fixing it up.

Also, while getting `make check` to run locally, I noticed a typo in configure.ac, so I'm going to add that fix to this branch.

**Comment by mhabrnal** [comment]
@bkylerussell Hello, thank you for the pull request, it seems the bug is not in your code but in DNF. There is a dependency issue while build root is installed. DNF is working on the issue.

**Comment by mkutlak** [comment]
test this please

**Comment by mkutlak** [comment]
DEBUG: RPM build errors:
DEBUG: error: File not found: /usr/bin/abrt-retrace-client
DEBUG: error: File not found: /usr/share/man/man1/abrt-retrace-client.1*
DEBUG: error: File not found: /etc/libreport/events.d/ccpp_retrace_event.conf
DEBUG: error: File not found: /usr/share/man/man5/ccpp_retrace_event.conf.5*
DEBUG:     File not found: /usr/bin/abrt-retrace-client
DEBUG:     File not found: /usr/share/man/man1/abrt-retrace-client.1*
DEBUG:     File not found: /etc/libreport/events.d/ccpp_retrace_event.conf
DEBUG:     File not found: /usr/share/man/man5/ccpp_retrace_event.conf.5*

**Comment by mkutlak** [comment]
You have to make some changes in spec file to fix your PR.

**Comment by bkylerussell** [comment]
Ah, sorry about that.  I remember thinking I needed to adjust the spec file but it slipped my mind.  Looks like I can reproduce this with `make rpm`, so I'll fix this and update the branch.

**Comment by bkylerussell** [comment]
I think I have things fixed up now.  The dash in the configure variable was actually tripping up the checks, so the default configuration wasn't what was expected.  Now the default build should still contain abrt-retrace-client (`make rpm` passes), but an rpm build `--without retrace` or `./configure --disable-retrace-client` also works, which was the goal.  Thanks for your consideration.

**Comment by mkutlak** [comment]
Rebased and I've made few changes in `configure.ac` to match the format of other similar options. 
The `--disable-retrace` was changed to `--without-retrace`

**Comment by mkutlak** [comment]
I've fixed the merge conflict.

**Comment by mkutlak** [comment]
Merging this PR as no one seems to be against it and it is quite old PR. 

Thank you @bkylerussell

**Pull request merged**
