### PR TITLE
Ccpp vulnerabilities

### PR DESCRIPTION
**Pull request by jfilak**
Requires: abrt/libreport#346
Requires: abrt/satyr#225

### CODE REVIEW

**Comment by sorki** [comment]
Care to explain how does 217e822 (ccpp: create dump directory without parents) makes the code safer?

**Comment by sorki** [comment]
I think it would be better if 96a1bb0 is split into two patches - one fixing simlink races and the oher one disabling java log saving.

**Comment by sorki** [comment]
@trapas test this please

**Comment by mbrysa** [comment]
#985 abrt-dbus should be restarted after abrt package update, otherwise it keeps loading dumpdirs from `/var/tmp/abrt` until killed.

**Comment by mbrysa** [comment]
abrt-cli must do chowning before reporting. Otherwise regular users cannot report koopes via cli.

**Comment by mbrysa** [comment]
After trying to report a koops using gnome-abrt as regular user, the DD is properly chowned to user:abrt, but the `.libreport/owner` still contains uid of nobody.

**Comment by mbrysa** [comment]
gnome-abrt must use d-bus to access problem details. Related https://github.com/abrt/gnome-abrt/issues/64 .

**Comment by mbrysa** [comment]
All the issues I pointed out are fixed in the latest rebase.

**Comment by mbrysa** [comment]
Thank you!

**Pull request merged**
