### PR TITLE
python-problem: Use the new D-Bus interface for watching

### PR DESCRIPTION
**Pull request by ernestask**
See commits. The other commit should also take care of things like https://bugzilla.redhat.com/show_bug.cgi?id=1740076.

### CODE REVIEW

**Comment by ernestask** [comment]
I honestly can’t think of any reason to keep the session objects around after the client disappears, because they might be reused by a completely different client, should the bus name be recycled, which could result in said client retaining authorization from before (not 100% sure on that, didn’t really follow the code).

**Comment by mgrabovsky** [comment]
I'm getting a segfault after opening and closing `gnome-abrt` with this.
```
Process 46823 (abrt-dbus) of user 0 dumped core.

Stack trace of thread 46823:
#0  0x00007f6ddfcc572b g_hash_table_lookup (libglib-2.0.so.0 + 0x3f72b)
#1  0x0000556337387c19 session_object_destructor (abrt-dbus + 0xac19)
#2  0x00005563373879f3 abrt_p2_object_free (abrt-dbus + 0xa9f3)
#3  0x00007f6ddff186c1 call_destroy_notify_data_in_idle (libgio-2.0.so.0 + 0x10c6c1)
#4  0x00007f6ddfcd447b g_idle_dispatch (libglib-2.0.so.0 + 0x4e47b)
#5  0x00007f6ddfcd87af g_main_context_dispatch (libglib-2.0.so.0 + 0x527af)
#6  0x00007f6ddfcd8b38 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52b38)
#7  0x00007f6ddfcd8e53 g_main_loop_run (libglib-2.0.so.0 + 0x52e53)
#8  0x000055633738544c main (abrt-dbus + 0x844c)
#9  0x00007f6ddfac8042 __libc_start_main (libc.so.6 + 0x27042)
#10 0x00005563373855ae _start (abrt-dbus + 0x85ae)

Stack trace of thread 46825:
#0  0x00007f6ddfb97aaf __poll (libc.so.6 + 0xf6aaf)
#1  0x00007f6ddfcd8ace g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52ace)
#2  0x00007f6ddfcd8e53 g_main_loop_run (libglib-2.0.so.0 + 0x52e53)
#3  0x00007f6ddff2e6aa gdbus_shared_thread_func (libgio-2.0.so.0 + 0x1226aa)
#4  0x00007f6ddfd02812 g_thread_proxy (libglib-2.0.so.0 + 0x7c812)
#5  0x00007f6ddfa88432 start_thread (libpthread.so.0 + 0x9432)
#6  0x00007f6ddfba2913 __clone (libc.so.6 + 0x101913)

Stack trace of thread 46826:
#0  0x00007f6ddfb9d37d syscall (libc.so.6 + 0xfc37d)
#1  0x00007f6ddfd27426 g_cond_wait_until (libglib-2.0.so.0 + 0xa1426)
#2  0x00007f6ddfca84c1 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x224c1)
#3  0x00007f6ddfca8b06 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22b06)
#4  0x00007f6ddfd031b9 g_thread_pool_thread_proxy (libglib-2.0.so.0 + 0x7d1b9)
#5  0x00007f6ddfd02812 g_thread_proxy (libglib-2.0.so.0 + 0x7c812)
#6  0x00007f6ddfa88432 start_thread (libpthread.so.0 + 0x9432)
#7  0x00007f6ddfba2913 __clone (libc.so.6 + 0x101913)

Stack trace of thread 46824:
#0  0x00007f6ddfb97aaf __poll (libc.so.6 + 0xf6aaf)
#1  0x00007f6ddfcd8ace g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52ace)
#2  0x00007f6ddfcd8c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
#3  0x00007f6ddfcd8c51 glib_worker_main (libglib-2.0.so.0 + 0x52c51)
#4  0x00007f6ddfd02812 g_thread_proxy (libglib-2.0.so.0 + 0x7c812)
#5  0x00007f6ddfa88432 start_thread (libpthread.so.0 + 0x9432)
#6  0x00007f6ddfba2913 __clone (libc.so.6 + 0x101913)
```

**Comment by ernestask** [comment]
Good catch, I’ll take a better look.

**Comment by ernestask** [comment]
Should be good now. Instead of cleaning up the object, I simply unregister it from the bus, which then results in destruction, so no double-freeing happens.

**Pull request merged**
