### PR TITLE
spec: split out some abrt events

### PR DESCRIPTION
**Pull request by jcpunk**
A fairly simple step one towards #1194 

It doesn't get all the examples separated out, but it is a start.

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
Good idea! I like this PR.

**Comment by jfilak** [comment]
ok to test

**Comment by jcpunk** [comment]
Just swinging back around on this one

**Comment by jfilak** [comment]
These commits close the PR:
https://github.com/abrt/abrt/commit/7a8cd8a07f5a8d619126163a368deb3b253ca5c5
https://github.com/abrt/abrt/commit/7e5e84bbe1460d45884c9eeee218838a0fd67688

Sorry for the delay!

**Pull request closed without merging**
