### PR TITLE
abrt-bodhi: use CCpp PackageManager configuration directive from conf…

### PR DESCRIPTION
**Pull request by arhledvink**
resolves #bz1357811
issue tracked as (no idea)
adds configure option
alters package manager directive in config file
suggests command with both package manager and previously omited repository
the test suite query is from live bodhi. not sure this is the best idea but...

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
add to whitelist

**Comment by jfilak** [comment]
test this please

**Comment by jfilak** [comment]
Thank you! I pushed commit https://github.com/abrt/abrt/commit/6858060e4d3ceb20464948967e87deb22b0d95da

**Pull request closed without merging**
