### PR TITLE
Add oops processing for kernel panics caused by hung tasks.

### PR DESCRIPTION
**Pull request by credmon**
Add oops processing for kernel panics; there was no search string in abrt-dump-oops that matched kernel panics caused by calling panic() in the linux kernel.

Example:
Kernel panic - not syncing: hung_task: blocked tasks
CPU: 3 PID: 27 Comm: khungtaskd Tainted: P           O    4.2.8-yocto-standard-1968fcd27440e21d39a0b9e14a3be2ad #1
Hardware name: xx (Device Tree)
Backtrace:
 ...

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
Thank you. Nice patch. I would like to ask you to add the example to https://github.com/abrt/abrt/tree/master/examples so we can use it in our tests:
* https://github.com/abrt/abrt/tree/master/tests/runtests/journal-oops-processing
* https://github.com/abrt/abrt/tree/master/tests/runtests/oops-processing

**Comment by credmon** [comment]
Examples have been added, and I made further improvements to the backtrace handling for ARM, since the oops is being added to the examples.

**Comment by jfilak** [comment]
Thank you. I have pushed the following commints:
f8aed1d testsuite: move examples to 'tests'
b788f65 testsuite: adapt oops test example outputs
63ae761 testsuite: add arm panic to koops processing
197a399 koops: do not assume version has 3 levels
a9222c0 Add ARM specific oops backtrace processing.
1cd68b0 examples:  add oops-kernel-panic-hung-tasks-arm
9299b31 Add oops processing for kernel panics caused by hung tasks.

**Pull request closed without merging**
