### PR TITLE
Refined forkflow for reporting to RHEL

### PR DESCRIPTION
**Pull request by mhabrnal**
Related: #1258474

### CODE REVIEW

**Comment by mhabrnal** [comment]
Requires https://github.com/abrt/libreport/pull/411

**Comment by jfilak** [comment]
retest this please

**Comment by jfilak** [comment]
retest this please

**Comment by mhabrnal** [comment]
retest this please

**Comment by mhabrnal** [comment]
retest this please

**Comment by mhabrnal** [comment]
retest this please

**Pull request merged**
