### PR TITLE
dbus: Additional changes to allow optional polkit

### PR DESCRIPTION
**Pull request by wlindauer**
Dbus problem2 API changes must have been in flight when I made the first
patch to disable polkit. This fixes the polkit functions I missed.

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
ok to test

**Comment by wlindauer** [comment]
@juliusmilan I have added a commit for applet.c. Let me know what you think.

**Comment by juliusmilan** [comment]
lgtm

**Pull request merged**
