### PR TITLE
a-a-c-o-f-hw-error: fix unicode error 2

### PR DESCRIPTION
**Pull request by hberan**
Fixes Red Hat Bugzilla Bug 1287302
The fix is the same kind as pull request https://github.com/abrt/abrt/pull/1099

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by mhabrnal** [comment]
Looks good to me, just erase the commit https://github.com/hberan/abrt/commit/d2630dfe0850887722f63aafd6ed0c656047aee0 from the pull request, please.

**Comment by patriczek** [comment]
Tested and it`s work for me

**Comment by mhabrnal** [comment]
Thank you!

**Pull request merged**
