### PR TITLE
Small refactorings

### PR DESCRIPTION
**Pull request by ernestask**
The current code that sets up hostname needles for searching the oops
haystack is a bit blegh. This commit simplifies it.

### CODE REVIEW

**Comment by ernestask** [comment]
The entire function caught my eye when investigating `abrt-dump-oops` failures, but it’s just too much for right now.

**Comment by ernestask** [comment]
@trapas retest this please

**Comment by ernestask** [comment]
Seems that libreport-devel isn’t being installed during the test job for some reason.

**Comment by ernestask** [comment]
Added another commit to fix `abrt-action-analyze-oops`.

**Comment by ernestask** [comment]
@trapas, retest this please

**Comment by mkutlak** [comment]
oops integration tests are passing with this patch :heavy_check_mark: 

LGTM

**Comment by ernestask** [comment]
@trapas, retest this please

**Comment by ernestask** [comment]
Wait, branch gone. Maybe I should pick a different PR.

**Pull request merged**
