### PR TITLE
cli-sanity: comment 'not reportable' phase out

### PR DESCRIPTION
**Pull request by martinky82**
it is not working in RHEL7

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by sorki** [comment]
Should go to rhel7 branch. Tests are now separated in branches.

**Comment by mhabrnal** [comment]
It goes to the rhel7 branch.

**Comment by sorki** [comment]
Ooops. Good then :)

**Comment by jfilak** [comment]
Thank you!

**Pull request merged**
