### PR TITLE
abrt-gui: wait for abrt to process problem directory

### PR DESCRIPTION
**Pull request by pkubatrh**
Abrt-gui now sets up an inotify watch if the problem directory is not processed yet.

closes rhbz#1012453

Signed-off-by: Petr Kubat pkubat@redhat.com

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by marusak** [comment]
Closing -  See #629  and 23eb68 .
I know that this PR is opened against RHEL6, but it is not going to be included.

**Comment by pkubatrh** [comment]
Yep, does not make sense to include this into rhel6 after all this time anymore.

**Pull request closed without merging**
