### PR TITLE
Add packages necessary for successful integration with Project Atomic

### PR DESCRIPTION
**Pull request by jfilak**
More details here : https://github.com/abrt/abrt/wiki/Containers-and-chroots#abrt---project-atomic

### CODE REVIEW

**Comment by mmilata** [comment]
Note: `yum install abrt\*` is no longer possible.

**Comment by mmilata** [comment]
Also `abrt-cli` cannot be installed due to dependency on `abrt-addon-ccpp`.

**Comment by mmilata** [comment]
Let's look into the subpackage dependencies tomorrow. Otherwise looks good!

**Comment by jfilak** [comment]
If you want ```abrt-cli``` **binary**, install ```abrt-tui``` **package**. Surprise :)

**Comment by jfilak** [comment]
Try ```yum install -x abrt-atomic abrt\*```.

**Comment by mmilata** [comment]
Seems to work fine ... merged, thank you!

**Pull request merged**
